# Generated by Django 3.2.7 on 2021-09-21 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('century', models.CharField(choices=[('40BC', '40BC'), ('39BC', '39BC'), ('38BC', '38BC'), ('37BC', '37BC'), ('36BC', '36BC'), ('35BC', '35BC'), ('34BC', '34BC'), ('33BC', '33BC'), ('32BC', '32BC'), ('31BC', '31BC'), ('30BC', '30BC'), ('29BC', '29BC'), ('28BC', '28BC'), ('27BC', '27BC'), ('26BC', '26BC'), ('25BC', '25BC'), ('24BC', '24BC'), ('23BC', '23BC'), ('22BC', '22BC'), ('21BC', '21BC'), ('20BC', '20BC'), ('19BC', '19BC'), ('18BC', '18BC'), ('17BC', '17BC'), ('16BC', '16BC'), ('15BC', '15BC'), ('14BC', '14BC'), ('13BC', '13BC'), ('12BC', '12BC'), ('11BC', '11BC'), ('10BC', '10BC'), ('9BC', '9BC'), ('8BC', '8BC'), ('7BC', '7BC'), ('6BC', '6BC'), ('5BC', '5BC'), ('4BC', '4BC'), ('3BC', '3BC'), ('2BC', '2BC'), ('1BC', '1BC'), ('1C', '1C'), ('2C', '2C'), ('3C', '3C'), ('4C', '4C'), ('5C', '5C'), ('6C', '6C'), ('7C', '7C'), ('8C', '8C'), ('9C', '9C'), ('10C', '10C'), ('11C', '11C'), ('12C', '12C'), ('13C', '13C'), ('14C', '14C'), ('15C', '15C'), ('16C', '16C'), ('17C', '17C'), ('18C', '18C'), ('19C', '19C'), ('20C', '20C'), ('21C', '21C')], default='21C', max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.location')),
                ('visitors', models.ManyToManyField(blank=True, null=True, to='mainapp.Visitor')),
            ],
        ),
    ]
