# Generated by Django 3.2.7 on 2021-09-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='organizer_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
