# Generated by Django 3.2.7 on 2021-09-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_item_organizer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
